//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotekaBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BibliotekaEntities : DbContext
    {
        public BibliotekaEntities()
            : base("name=BibliotekaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autorzy> Autorzies { get; set; }
        public virtual DbSet<Ksiazki> Ksiazkis { get; set; }
        public virtual DbSet<Studenci> Studencis { get; set; }
        public virtual DbSet<TypKsiazki> TypKsiazkis { get; set; }
        public virtual DbSet<Wypozyczenia> Wypozyczenias { get; set; }
    }
}
